class KeyAction:
    PRESS = "press"
    REPEAT = "repeat"
    RELEASE = "release"


class Keys:
    # Letters
    A = "a"
    B = "b"
    C = "c"
    D = "d"
    E = "e"
    F = "f"
    G = "g"
    H = "h"
    I = "i"
    J = "j"
    K = "k"
    L = "l"
    M = "m"
    N = "n"
    O = "o"
    P = "p"
    Q = "q"
    R = "r"
    S = "s"
    T = "t"
    U = "u"
    V = "v"
    W = "w"
    X = "x"
    Y = "y"
    Z = "z"

    # Arrows
    UP = "up"
    DOWN = "down"
    LEFT = "left"
    RIGHT = "right"

    # Common keys
    SPACE = "space"
    ESCAPE = "escape"
    ENTER = "enter"
    TAB = "tab"
    BACKSPACE = "backspace"
    LEFT_SHIFT = "left_shift"
    RIGHT_SHIFT = "right_shift"
    LEFT_CTRL = "left_ctrl"
    RIGHT_CTRL = "right_ctrl"
    LEFT_ALT = "left_alt"
    RIGHT_ALT = "right_alt"
    INSERT = "insert"
    HOME = "home"
    PAGE_UP = "page_up"
    DELETE = "delete"
    END = "end"
    PAGE_DOWN = "page_down"

    # Function keys
    F1 = "f1"
    F2 = "f2"
    F3 = "f3"
    F4 = "f4"
    F5 = "f5"
    F6 = "f6"
    F7 = "f7"
    F8 = "f8"
    F9 = "f9"
    F10 = "f10"
    F11 = "f11"
    F12 = "f12"

    # Numbers
    NUMBER_0 = "0"
    NUMBER_1 = "1"
    NUMBER_2 = "2"
    NUMBER_3 = "3"
    NUMBER_4 = "4"
    NUMBER_5 = "5"
    NUMBER_6 = "6"
    NUMBER_7 = "7"
    NUMBER_8 = "8"
    NUMBER_9 = "9"

    # Numpad numbers
    NUMPAD_0 = "numpad_0"
    NUMPAD_1 = "numpad_1"
    NUMPAD_2 = "numpad_2"
    NUMPAD_3 = "numpad_3"
    NUMPAD_4 = "numpad_4"
    NUMPAD_5 = "numpad_5"
    NUMPAD_6 = "numpad_6"
    NUMPAD_7 = "numpad_7"
    NUMPAD_8 = "numpad_8"
    NUMPAD_9 = "numpad_9"

class MouseButtons:
    LEFT = "left"
    RIGHT = "right"
    MIDDLE = "middle"